### ISSUE TITLE
Difference from original code

### ISSUE THREAD

**Issue by taki0112** [luoxier/CycleGAN_Tensorlayer#1]
HI
very nice implemented cyclegan
I have a few questions...

1. What does "Resize Convolution" mean?
2. I wonder what is different from the original code of the author.

**Comment by luoxier** [comment]
Thank you for your questions. 
1. About Resize Convolution you can refer to link https://distill.pub/2016/deconv-checkerboard/. It is used to remove checkerboard artifacts which commonly occur in images generated by deconvolution.
2. In fact, the main goal is to study and re-implement in Tensotlayer ( framework difference).  And then add some tricks to improve the quality of output images. (1. Each group in datasets has just more than 1000 images, by enlarging dataset using data augmentation maybe we can obtain better results; 2.  The original paper mentioned the BatchNorm in the architecture of networks and when I refer to implementation in GitHub, most implementation updates to the InstanceNorm, and actually InstanceNorm may perform better in style transfer to some extent; 3. Some checkerboard artifacts in output images can be removed by replacing deconv with resize-conv in decoder part.  )

**Comment by taki0112** [comment]
If you look at main.py, you used model_upsampling.py. Is this resize_conv you say? 

If so, will it be the same as the original cyclegan if I use model_deconv.py?

**Comment by zsdonghao** [comment]
resize cov = upsampling + conv

**Comment by Zxr1314** [comment]
@zsdonghao  hello，tensorlayer‘s author. resize conv is just as unet's done?

**Comment by zsdonghao** [comment]
@Zxr1314 check this https://distill.pub/2016/deconv-checkerboard/

**Comment by Zxr1314** [comment]
@zsdonghao thank u very much，a detailed explanation for deconv

**Comment by Zxr1314** [comment]
@zsdonghao effect of resize-conv is really useful for GAN，thanks again！
